blueprint:
  name: Radon – Exakte Schätzung des aktuellen Werts (variabler Abstand)
  description: >
    Berechnet den geschätzten aktuellen Radonwert auf Basis des alten und neuen
    24h-Mittelwerts sowie der Zeitdifferenz. Speichert das Ergebnis in einem Input Number.
  domain: automation

  input:
    mittelwert_sensor:
      name: 24h-Mittelwert-Sensor
      selector:
        entity:
          domain: sensor
    altwert_input_number:
      name: Alter Mittelwert (Input Number)
      selector:
        entity:
          domain: input_number
    geschaetzt_input_number:
      name: Schätzwert speichern in (Input Number)
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input mittelwert_sensor

action:
  - variables:
      m_neu: "{{ states(input.mittelwert_sensor) | float(
