blueprint:
  name: Radon – Exakte Schätzung des aktuellen Werts (variabler Abstand)
  description: >
    Berechnet den geschätzten aktuellen Radonwert auf Basis des alten und neuen
    24h-Mittelwerts sowie der Zeitdifferenz. Speichert das Ergebnis in einem Input Number.
  domain: automation

  input:
    mittelwert_sensor:
      name: 24h-Mittelwert-Sensor
      selector:
        entity:
          domain: sensor
    altwert_input_number:
      name: Alter Mittelwert (Input Number)
      selector:
        entity:
          domain: input_number
    geschaetzt_input_number:
      name: Schätzwert speichern in (Input Number)
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input mittelwert_sensor

action:
  - service: input_number.set_value
    target:
      entity_id: !input geschaetzt_input_number
    data:
      value: >
        {% set m_neu = states('{{ i.mittelwert_sensor }}') | float(0) %}
        {% set m_alt = states('{{ i.altwert_input_number }}') | float(0) %}
        {% set dt = (as_timestamp(now()) - as_timestamp(states('{{ i.mittelwert_sensor }}').last_changed)) / 3600 %}
        {% if dt > 0 %}
          {{ ((m_neu * 24 - m_alt * (24 - dt)) / dt) | round(1) }}
        {% else %}
          0
        {% endif %}

  - service: input_number.set_value
    target:
      entity_id: !input altwert_input_number
    data:
      value: >
        {{ states('{{ i.mittelwert_sensor }}') | float(0) }}

mode: single
