blueprint:
  name: Radon – Exakte Schätzung des aktuellen Werts (variabler Abstand)
  description: >
    Berechnet den geschätzten aktuellen Radonwert auf Basis des alten und neuen 24h-Mittelwerts
    sowie der Zeitdifferenz. Speichert das Ergebnis in einem Input Number.
  domain: automation

  input:
    mittelwert_sensor:
      name: 24h-Mittelwert-Sensor
      selector:
        entity:
          domain: sensor
    altwert_input_number:
      name: Alter Mittelwert (Input Number)
      selector:
        entity:
          domain: input_number
    geschaetzt_input_number:
      name: Schätzwert speichern in (Input Number)
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input mittelwert_sensor

variables:
  mittelwert_entity: !input mittelwert_sensor
  altwert_entity: !input altwert_input_number

action:
  - variables:
      m_neu: "{{ states(mittelwert_entity) | float(0) }}"
      m_alt: "{{ states(altwert_entity) | float(0) }}"
      dt: >
        {{ (as_timestamp(now()) - as_timestamp(states[mittelwert_entity].last_changed)) / 3600 }}
      wert: >
        {% if dt > 0 %}
          {{ ((m_neu * 24 - m_alt * (24 - dt)) / dt) | round(1) }}
        {% else %}
          0
        {% endif %}

  - service: input_number.set_value
    target:
      entity_id: !input geschaetzt_input_number
    data:
      value: "{{ wert }}"

  - service: input_number.set_value
    target:
      entity_id: !input altwert_input_number
    data:
      value: "{{ m_n_
